apiVersion: v1
kind: Service
metadata:
  name: my-asp-app
  labels:
    app: my-asp-app
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: my-asp-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-asp-app
  name: my-asp-app
spec:
  selector:
    matchLabels:
      app: my-asp-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-asp-app
      name: my-asp-app
    spec:
      tolerations:
      - key: "os"
        value: "Windows"
        Effect: "NoSchedule"
      containers:
      - name: sampledotnetapp
        image: quay.io/tprinz/my-asp-app
        imagePullPolicy: IfNotPresent
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: my-asp-app
  name: my-asp-app
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: my-asp-app
    weight: 100
  wildcardPolicy: None
